const BASE_URL = "https://www.richardwhudsonjr.com";

function generateSiteMap(paths) {
  return `<?xml version="1.0" encoding="UTF-8"?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      ${paths
        .map((path) => {
          return `
            <url>
              <loc>${`${BASE_URL}${path}`}</loc>
              <lastmod>${new Date().toISOString()}</lastmod>
              <changefreq>monthly</changefreq>
              <priority>${path === "/" ? "1.0" : "0.8"}</priority>
            </url>
          `;
        })
        .join("")}
    </urlset>
  `;
}

export default function SiteMap() {
  // This file is auto-generated by getServerSideProps
  return null;
}

export async function getServerSideProps({ res }) {
  try {
    // Dynamically define the paths for your website
    const paths = [
      "/",
      "/about",
      "/projects",
      "/resume",
      "/consult",
      "/contact", // Newly added Contact page
    ];

    // Generate the sitemap content
    const sitemap = generateSiteMap(paths);

    // Set headers and send the sitemap
    res.setHeader("Content-Type", "text/xml");
    res.write(sitemap);
    res.end();

    return {
      props: {},
    };
  } catch (error) {
    console.error("Error generating sitemap:", error);

    // Provide fallback props in case of an error
    return {
      props: {},
    };
  }
}
